chore: Update mathlib revision, fixing a conflict (#467)
[This
commit](https://github.com/leanprover-community/mathlib4/commit/ed4fde18eec46c041fd609768b16dee361fa6018#diff-54ef6c59abdddf67950b1ee785a0c22c7e03d04f9ad8cdb7cf1d336a72f4d850)
in mathlib4 moves `foldl_eq_foldr` to another module, so we need to
import it or the build fails with

```lean
error: Cslib/Computability/URM/Basic.lean:178:27: Unknown constant `List.foldl_eq_foldr`
```

This PR updates the lake manifest past this commit with `lake update
mathlib` and fixes the issue